- scripts/flow-staged.sh
Path is already updated by @fubhy 
@nikgraf FYI
> Updated flow installation instructions

- package.json
- scripts/stylint-staged.sh
This PR should add support for the stylint linter
> Added stylint support

- src/index.js
> Incorrect condition

- package.json
- src/runScript.js
> Fix errors to OS Windows

- index.js
See <https://nodejs.org/api/modules.html#modules_all_together>.
> Remove unnecessary "index" in "require"

- README.md
- src/index.js
I've added the possibility to set the git-root which if set will be used to resolve the filepaths accordingly
this should fix: #41
> Running Lint-staged from within a sub directory

- CHANGELOG.md
- src/runScript.js
> Output both stderr and stdout

- src/index.js
- src/resolvePaths.js
Fix so the paths will be properly resolved and working when the git directory differs from the current working directory
> Fix for working in subdir

- package.json
- src/index.js
- src/runScript.js
No need to force colors in GUIs. Closes #106
> Force colors only when running in TTY

- .travis.yml
- package.json
> Enabled semantic release

- src/index.js
- src/runScript.js
> When rejecting, use new Error and error.message respectively.

- README.md
- src/findBin.js
- src/index.js
- src/runScript.js
- test/findBin.spec.js
- test/generateTasks.spec.js
- test/runScript.spec.js
This PR introduces verbose mode. In verbose mode https://github.com/SamVerschueren/listr-verbose-renderer is being used by default. Useful when debugging lint-staged.
> Feat: verbose mode

- .travis.yml
- package.json
- src/findBin.js
- test/__fixtures__/test.css
- test/__fixtures__/test.js
- test/__fixtures__/test.txt
- test/__mocks__/execa.js
- test/__mocks__/npm-which.js
- test/findBin.spec.js
- test/runScript.spec.js
- wallaby.js
> Use 🃏 Jest as a testing framework

- package.json
Closes #145
https://greenkeeper.io/
> chore(package): update eslint-config-okonet to version 4.0.0

- package.json
Only these files (without test files etc.):
- `package.json`
- `README.md`
- `LICENSE`
- `index.js`
- `src/*`
See https://docs.npmjs.com/files/package.json#files
> feat: restrict to only necessary files for distribution

- package.json
> Remove unportable postinstall.

- package.json
> chore(package): update remove-lockfiles to version 1.1.1

- package.json
- test/generateTasks.spec.js
> chore(package): update eslint-config-okonet to version 5.0.1

- src/index.js
- test/__snapshots__/index.spec.js.snap
- test/index.spec.js
> feat: Better error handling if config is missing

- package.json
@okonet @sudo-suhas 
This is a super important bugfix.. We accidentally introduced a breaking change!
I missed this in #250 😭 
See https://travis-ci.org/luftywiranda13/generator-node-oss/jobs/275875611#L450
Closes #284
> fix: missing entry file

- src/findBin.js
- src/runScript.js
- test/findBin.spec.js
> fix(findBin): Add separator before npm args

- test/resolveGitDir.spec.js
Found the same issue #300 in another test.
> Change process.env.HOME to os.tmpdir

- package.json
- src/runAll.js
- test/__snapshots__/runAll.spec.js.snap
- test/resolveGitDir.spec.js
- test/runAll.spec.js
I am trying to solve this [issue](https://github.com/okonet/lint-staged/issues/259) but I have little time. So I will solve the issue in chunks.
I will be glad if you will point out any mistakes
> Add full coverage for runAll.js

- package.json
- src/runAll.js
This uses `pify` to promisify callback-style `staged-git-files`.
> refactor: Promisify staged-git-files

- package.json
- src/runScript.js
- test/getConfig.spec.js
- test/index.spec.js
- test/printErrors.spec.js
- test/runAll.spec.js
- test/runScript.spec.js
- `consolemock {0.3.0 🡲 1.0.2}`
- `prettier {1.7.4 🡲 1.8.2}`
> chore(package): Bump dev-dependencies

- test/__mocks__/npm-which.js
- test/generateTasks.spec.js
- test/getConfig.spec.js
- test/index.spec.js
- test/printErrors.spec.js
- test/runAll.spec.js
- test/runScript-mock-findBin.spec.js
- test/runScript-mock-pMap.spec.js
- test/runScript.spec.js
> test: Optimise assertions, mocks and test hooks

- package.json
The closing brace was missed somehow 🤷‍♂️
> chore(package): Add closing braces for maintainers

- .github/issue_template.md
Closes #340.
Link: [okonet/lint-staged:.github/issue_template.md@`chore/issue-template` (raw)](https://raw.githubusercontent.com/okonet/lint-staged/3f6f4d7a8795b6c6c5af0b1be0fd952aa1396e87/.github/issue_template.md)
> chore(github): Add issue template

- README.md
Closes #151 .
@okonet Let me know if this should be in a different area of the Readme or if you have any other changes you'd like to see.
And thanks for this project. I'm proud to contribute, however small it may be!
> Add JetBrains IDE instructions for bugfix

- .gitignore
- README.md
- src/index.js
Also sneak in a couple of insignificant changes.
> docs: Link to AgentConf talk by @okonet

- .lintstagedrc.json
- package.json
- test/__snapshots__/findBin.spec.js.snap
> chore: Use npm as script runner

- README.md
As discuss here https://github.com/okonet/lint-staged/issues/471#issuecomment-402998754
Update Reame file for advance configuration.
Hope this will save some time to future users.
> Update documentation for advance usage

- README.md
Some small improvements and spelling fixes.
> docs: Readme edits for spelling and grammar

- package.json
- src/findBin.js
- yarn.lock
See https://github.com/okonet/lint-staged/pull/477#issuecomment-410927383
> fix: Make app package.json load error tolerant

- src/gitWorkflow.js
> fix(git): Use resolveGitDir in hasPartiallyStagedFiles

- package.json
- yarn.lock
> fix: Use listr-update-renderer from npm

- README.md
"Automatically fix code" should work out of the box, hunks commits and linter failures work fine.
> README: Remove comment about hunks support

- package.json
Reverts okonet/lint-staged#538
> Revert "chore: pin cosmiconfig to 5.0.6"

- test/gitStash.spec.js
1. When I download the repository, I do not pass tests right away.
2. If I want to suggest my changes for this library, I can’t do a full test and make sure everything works.
> Fixed tests for windows

- README.md
This PR adds an example of ignoring files from the match, via function linter
> docs: add ignore glob example

- README.md
This PR fixes the `beta` tag to the README's section about v10. I used a `fix` type commit to make sure it gets updated on npm.
> fix: update README for beta tag

- README.md
- bin/lint-staged
- src/index.js
- src/runAll.js
- test/runAll.unmocked.spec.js
Supports <boolean | number> (true/false, max number of tasks to run concurrently).
I don't love the tests, but I'm open to suggestions on how to improve them.
> Add support for concurrent CLI option

- .lintstagedrc.json
- README.md
- lib/gitWorkflow.js
- lib/resolveTaskFn.js
- lib/runAll.js
- package.json
- test/__snapshots__/index.spec.js.snap
- test/__snapshots__/runAll.spec.js.snap
- test/makeCmdTasks.spec.js
- test/resolveTaskFn.spec.js
- test/resolveTaskFn.unmocked.spec.js
- test/runAll.unmocked.2.spec.js
- test/runAll.unmocked.spec.js
- yarn.lock
This PR fixes a bunch of v10 issues. The commit messages are self-explanatory and thus this should be merged without squashing.
Fixes https://github.com/okonet/lint-staged/issues/770
Potentially fixes https://github.com/okonet/lint-staged/issues/771 because the error message is more clear
Fixes https://github.com/okonet/lint-staged/issues/773 at least in the simple cases
> Fix a bunch of v10 issues

- .github/workflows/main.yml
See https://github.blog/changelog/2019-10-01-github-actions-new-workflow-syntax-features/#if-at-the-job-level
> ci: get event name from correct place

- README.md
There was a bug! If there were no changed files `prettier --write` would run, which for some reason causes a hang. Not sure if that is a bug in itself.
> fix bug in automatic prettier example

- README.md
Hey team, I went through the README this morning and came across a few minor errors. I did some proofreading for you and have submitted these changes here. Hope that helps!
> docs: corrects minor typos and grammar in README

- package-lock.json
- package.json
> fix: remove `npm` version requirement

- lib/getDiffCommand.js
- lib/getStagedFiles.js
- lib/gitWorkflow.js
- lib/runAll.js
- test/unit/getDiffCommand.spec.js
Closes issue https://github.com/okonet/lint-staged/issues/1175
> Extract diff string generation to unify diffs across library

- README.md
Fixes broken configuration link.
> Fix: Point to correct configuration link

- .changeset/lovely-seas-wait.md
- package-lock.json
- package.json
This should fix issue #1338 by updating `listr2@7.0.2`.
> fix(deps): update dependencies

- .github/workflows/tag.yml
See also https://docs.npmjs.com/generating-provenance-statements#example-github-actions-workflow
> chore: generate provenance statements for npm package

- .changeset/tidy-planets-pretend.md
- bin/lint-staged.js
Closes https://github.com/lint-staged/lint-staged/issues/1499
> fix: handle possible failures when logging user shell for debug info

- .changeset/rare-pans-pretend.md
- .changeset/soft-zoos-accept.md
- lib/configFiles.js
- package.json
Closes https://github.com/lint-staged/lint-staged/issues/1503
> Fix new TypeScript features

- .changeset/wise-weeks-check.md
- README.md
- bin/lint-staged.js
- lib/gitWorkflow.js
- lib/index.js
- lib/messages.js
- lib/runAll.js
- test/e2e/no-stash.test.js
- test/integration/no-stash.test.js
- test/unit/runAll.spec.js
> fix: using `--no-stash` flag doesn't add unstaged changes to partially staged files

- .changeset/empty-hoops-shake.md
- lib/messages.js
- test/e2e/no-stash.test.js
- test/integration/no-initial-commit.test.js
- test/integration/no-stash.test.js
- test/unit/runAll.spec.js
Related to https://github.com/lint-staged/lint-staged/issues/1468
> fix: warn about potential data loss when using "--no-stash"

- README.md
- jest.config.js
- lib/chunkFiles.js
- test/integration/allow-empty.test.js
- test/unit/state.spec.js
> chore: fix typos

- lib/gitWorkflow.js
replace deprecated substr with slice
> refactor: replace deprecated substr with slice

- .changeset/late-readers-brush.md
- bin/lint-staged.js
- lib/gitWorkflow.js
- lib/index.js
- lib/messages.js
- lib/state.js
- lib/symbols.js
- test/integration/fail-on-changes.test.js
- test/unit/index3.spec.js
> Fail on changes reset
