lint-staged/lint-staged

package.json
src/index.js

Hi, I liked this module and would like to utilize this in some of my codebases, sending PR to enhance couple of behavior.
- resolve root path via app-root-path, provides platform compatible path
: Usually for Windows user who runs different shells will have issues by determining root via `git` can returns shell-specific path like `\c\apps\myapp...`. instead, introduced `app-root-path` (https://github.com/inxilpro/node-app-root-path) to resolve root path to application.
- fixes npm-which invocation to correctly resolves npm
one thing I noticed is this module calls `npm-which` with name of `linter` as `npmWhich(linter,...)` which causes npm-which fails all time since npm-which expects file to lookup (npm, in this case). Updated to lookup npm, leave fallback to default binPath as-is.

[fix] update path resolution to npm

---

package.json
src/index.js
src/runScript.js
test/runScript.spec.js

Added support for sequences of commands

---

src/findBin.js
test/findBin.spec.js

In testing `lint-staged` for #41 and found that `lint-staged` doesn’t work if `package.json` has no `scripts` section.
This little PR fixes it.

Work with no scripts in package.json

---

package.json

In `babel-core/register.js`:
```js
/* eslint max-len: 0 */
// TODO: eventually deprecate this console.trace("use the `babel-register` package instead of `babel-core/register`");
module.exports = require("babel-register");
```

Use babel-register instead of babel-core/register

---

.eslintrc

See <https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-extraneous-dependencies.md>.

Improve ESLint import rule setting

---

README.md

Did this mistake in the last step myself ;-|

Tweak installation instructions a little

---

README.md

It’s simpler and probably more common. Never seen `@(js|jsx)` but something like `{js,jsx}` I use very often.

Show simpler pattern for matching js/jsx

---

package.json

Allows using https://github.com/commitizen/cz-cli with https://www.npmjs.com/package/cz-conventional-changelog to improve commit messages
So, instead of
```bash
git commit
```
please do
```bash
git cz
```

chore: Added commitizen conventional changelog

---

src/generateTasks.js
test/generateTasks.spec.js

minimatch has option { dot: false } by default. This should enable better glob matching for paths
with dots.
Closes #91

fix(glob): Added dot: true to allow more complex globs with dots in path

---

src/index.js
src/runScript.js
test/runScript.spec.js

In case of running lint-stage from a sub-directory,
execa should be also run with `cwd` option set correctly to the git dir.
Closes #109

If `gitDir` is set pass it as `cwd` option to execa

---

package.json
src/resolvePaths.js
test/resolvePaths.spec.js

Fixes #115 by making resolvePaths() return paths that are relative to CWD. Should gitDir be set to `..`, the returned path for `alpha.js` would be `../alpha.js`.
I haven't looked too closely at all of the path computations, but it feels like this could be simplified further.

fix(resolvePaths): return CWD-relative paths - closes #115

---

src/runScript.js

On Windows, if the same `execaOptions` are re-used for running 'linters' in [runScripts.js](/okonet/lint-staged/blob/master/src/runScript.js) `windowsVerbatimArguments: true` options will be added  which breaks the `git add` command if present with following error:
```
{ Error: spawn undefined ENOENT
at notFoundError (E:\workspace\odyssey\node_modules\cross-spawn\lib\enoent.js:11:11)
at verifyENOENT (E:\workspace\odyssey\node_modules\cross-spawn\lib\enoent.js:46:16)
at ChildProcess.cp.emit (E:\workspace\odyssey\node_modules\cross-spawn\lib\enoent.js:33:19)
at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
errno: 'ENOENT',
code: 'ENOENT',
syscall: 'spawn undefined',
killed: false,
stdout: '',
stderr: 'git: \'Files\\Git\\cmd\\git.EXE\' is not a git command. See \'git …
```

Bug fix for issue #114

---

package.json
src/index.js

When running tasks in parallel (which is by default), we want to run all linters
and display all errors after they finished their work.
Fixes #86

Fix: Wait for all tasks to finish before showing errors

---

src/generateTasks.js
src/index.js
test/generateTasks.spec.js

This is an initial attempt at a solution for #135. In short, I'm adjusting the `generateTasks` function so it doesn't filter out patterns with no matching files, and then adding a special case for tasks with no files found.
There's another option for this that involves just adding the logging to the `generateTasks` function, which could keep the main method a little less complicated if that's preferred.
I'm also noticing that there seems to be an inconsistency between the check character that lint-staged uses, `✅`, and the one that Listr seems to use, `✔`. This isn't a new problem, but it does look a little odd now:

Adding logging for when no files match a pattern.

---

src/runScript.js
test/__mocks__/execa.js
test/runScript-mock-findBin.spec.js
test/runScript.spec.js

+ changing `res.bin !== 'npm'` to `res.bin === 'git'`
It's not possible to get the getDir path for git specific executions, in underlying directory paths and doing a precommit for lint-staged. Using `'git'` options specifically declares to use options that include the getDir option for doing precommits.   
---
<details>
<summary>Error report</summary>
<pre><code>SyntaxError: Unexpected token import at transformAndBuildScript (gui/node_modules/jest-
runtime/build/transform.js:320:12)
</code></pre>
</p></details>
Closes #158

Fix gitDir Bug for git specific executables

---

src/runScript.js

git detection didn't take file extension into consideration which caused an error when using git task on windows
fix #117

fix gitDir on windows

---

README.md
src/generateTasks.js
test/generateTasks.spec.js

Adds the `globOptions` key to advanced config to allow customisation of how matching works.
Will also solve (although it is not a bug in hindsight but not ideal either): https://github.com/okonet/lint-staged/issues/173

Add advanced option globOptions to customise how matching works

---

.eslintrc
package-lock.json

due to test framework migration from `mocha` to `jest`,
`eslint` env should also be set to `jest`

chore(eslint): set environment to reflect #9e79050

---

package.json

Sets jest config in `package.json`. Reference docs - https://facebook.github.io/jest/docs/en/configuration.html#testenvironment-string

chore: Set jest env as node to avoid jsdom overhead

---

src/runScript.js
test/runScript-mock-findBin.spec.js
test/runScript.spec.js

Closes #195 
BREAKING CHANGE: This might affect existing setups which depend on the `--` argument.

feat: Skip '--' argument for non-npm commands

---

src/index.js

E.g. when invoked by a `package.json` in a subdirectory:
```
$ git commit -m "Reformat-on-commit"
Found '/Users/seth/src/hotosm/osm-export-tool2/ui/.nvmrc' with version <6>
Now using node v6.11.0 (npm v3.10.10)
Found '/Users/seth/src/hotosm/osm-export-tool2/ui/.nvmrc' with version <6>
Now using node v6.11.0 (npm v3.10.10)
husky > npm run -s precommit (node v6.11.0)
Error: fatal: Not a git repository: '.git'
at ChildProcess.<anonymous> (/Users/seth/src/hotosm/osm-export-tool2/ui/node_modules/staged-git-files/index.js:85:19)
at emitTwo (events.js:106:13)
at ChildProcess.emit (events.js:191:7)
at maybeClose (internal/child_process.js:891:16)
at Socket.<anonymous> (internal/child_process.js:342:11)
at emitOne (events.js:96:13)
at Socket.emit (events.js:188:7)
at Pipe._handle.close [as …
```

Bail on fatal errors

---

README.md
src/runScript.js

This sets the default `subTaskConcurrency` as `1` to disable parallel execution of chunks. I have also updated the readme.
Closes #225

fix: Disable concurrent sub task execution by default

---

.travis.yml
package.json

- We almost never run `semantic-release` manually, I see *no* benefit to have it listed in devDependencies
- We're still using the old version of `semantic-release` which produces annoying `<a name"blahblah">` in releases page. It's solved in v7
- Moving `semantic-release` to CI will reduce the time it takes to install devDependencies
- Installing `semantic-release` gives us some warnings in CLI output
I did this to some projects such as:
- [generator-node-oss](https://github.com/luftywiranda13/generator-node-oss)
- [remove-lockfiles](https://github.com/luftywiranda13/remove-lockfiles)
- [glamorous](https://github.com/paypal/glamorous)
- [polished](https://github.com/styled-components/polished), etc.
<p align="center"><strong>Before:</strong> <em>4 warnings</em></p>
<p …

chore: move `semantic-release` to Travis

---

.travis.yml

Since we don't allow committing lockfiles in this repo,
I think it's best to also not cache `node_modules` in Travis CI
* Grab fresh dependency trees
* This will help us to catch any regressions introduced by our dependencies
* Caching `node_modules` in Travis also causes more harm than benefit
because in some cases we need to clear the cache to make our tests pass in Travis
(Like what we did in #231)
It'll take more time for Travis to finish the jobs

ci: Don't cache `node_modules`

---

.babelrc
package.json

Hi it's me cleaning up again 😂
I notice that we're using some unnecessary babel packages as devDependencies.
https://github.com/okonet/lint-staged/blob/a28463d86aab05e0e00d1bd5b1b3985cbe0f4c26/package.json#L64-L69
I think the reason why we have them is to make it easier to write our tests (async/await, promise, etc.)
We can safely remove some of them. 
By submitting this PR, I propose to remove some babel packages so we'll only have two babel packages left.
```js
{
"babel-jest": "^20.0.0",
"babel-preset-env": "^1.4.0",
// other deps
}
```
- I uninstalled the packages
- I ran our tests `npm test`  🎉

chore: Remove unnecessary `babel` packages

---

package.json

We only use `jsonlint` in this project,
https://github.com/okonet/lint-staged/blob/e3b7fafa63466ab854718222795210e59338703e/.lintstagedrc#L7
So it's safe to remove the unused `jsonlint-cli`

chore: Remove `jsonlint-cli`

---

package.json
src/.eslintrc.json
src/index.js

In order to ensure that we don't use ES2015 features that doesn't work in Node 4.x, I've added this ESLint plugin with the set of recommended rules.

chore: Add eslint-node-plugin with the recommended configuration

---

appveyor.yml
src/runAll.js
test/__mocks__/execa.js
test/generateTasks.spec.js
test/resolveGitDir.spec.js
test/runScript-mock-findBin.spec.js
test/runScript-mock-pMap.spec.js
test/runScript.spec.js

This PR does the following:
- Fixes test failures due to path comparison by using a test-work directory and `path.normalize`. The test-work directory is set to `path.join(process.env.HOME, 'tmp-lint-staged')`. `process.env.HOME`, or `$HOME` is `C:\\Users\\username` on windows and `/home/username` on *nix.
- Fixes a bug in `runAll` caused by not returning from function when `staged-git-files` returns an error. 
- Fixes an issue with the appveyor config due to shallow clone which results in error `fatal: Not a git repository`.
- Fixes the blinking test by refactoring jest mocks. Now all tests pass on appveyor 🎉
```
Test Suites: 2 failed, 9 passed, 11 total
Tests:       8 failed, 50 passed, 58 total
Snapshots:   13 passed, 13 total
Time:        2.534s
Ran all test suites.
```
<details> …

test: Fix failing tests on Windows

---

test/runAll.spec.js

Since the implementation was already merged in #255, this PR only adds a test. It will trigger semantic-release to actually release the new version.
Closes #264

fix: Handle the case when staged-git-files errors properly

---

.travis.yml
appveyor.yml

For pull requests which are made from a branch in this repo instead of a fork, travis and appveyor run duplicate builds once for the PR and once for the branch push. See example - https://github.com/okonet/lint-staged/pull/250. By whitelisting branches, we can limit builds to master, PRs and greenkeeper branches.

ci: Whitelist build branches to avoid duplicate builds

---

appveyor.yml

@okonet This was a rather trivial change and a lot of issues from greenkeeper are stemming from this. So I tried to push this commit to master:
```
λ git push origin master
Counting objects: 3, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 319 bytes | 159.00 KiB/s, done.
Total 3 (delta 2), reused 0 (delta 0)
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: 3 of 3 required status checks are expected. At least one approved review is required by reviewers with write access.
To https://github.com/okonet/lint-staged
! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs …
```

ci(appveyor): Switch off node modules cache

---

src/findBin.js
src/index.js
src/runAll.js
src/runScript.js
test/findBin.spec.js
test/runAll.spec.js
test/runScript.spec.js

fix(findBin): Resolve package script with args

---

src/findBin.js

This adds code comment explaining why `--` is required even if args might not be defined.

docs: Add code comment for func findBin>npmArgs

---

README.md
index.js
package.json
src/index.js
test/__mocks__/cosmiconfig.js
test/__mocks__/my-config.json
test/__snapshots__/index.spec.js.snap
test/index.spec.js

I use `lint-staged` as a pre-commit hook and would like to explicitly provide the config file location. This PR uses [`commander`](npmjs.com/package/commander) to parse the command-line argument and passes it as `cosmiconfig`'s [`configPath`](https://github.com/davidtheclark/cosmiconfig#configpath) option. This allows the config file to be any format already supported.
I've added tests and updated the documentation.

Allow config to be provided via command-line

---

README.md

Right now, we have 2 build badges which look exactly the same:
And it bothers me just a little bit 😅. This PR tweaks the appveyor badge as shown below.
Appveyor docs - https://www.appveyor.com/docs/status-badges/

docs: Tweak appveyor badge

---

package.json
src/index.js
test/index.spec.js

- Bump cosmiconfig {`1.1.0` ➡ `3.1.0`}, refactor usage.
- Remove greenkeeper directive for ignoring cosmiconfig.
- Update test mock impls for new cosmiconfig API.
Closes #282.

chore: Bump cosmiconfig to v3, rm greenkeeper ignore

---

package.json
src/getConfig.js
src/index.js
src/runScript.js
test/__snapshots__/index.spec.js.snap
test/runScript-mock-pMap.spec.js
test/runScript.spec.js

This PR uses [`dedent`](https://www.npmjs.com/package/dedent) for beautifying multi-line template literals:
```js
const dedent = require('dedent');
// ...
// Before
console.log(`This is a multi-line
sentence`);
// After
console.log(dedent`
This is a multi-line
sentence
`)
```

style: Use dedent for prettier multi-line template literals

---

README.md
package.json
src/generateTasks.js
src/getConfig.js
src/resolveGitDir.js
src/runAll.js
src/runScript.js
test/__snapshots__/getConfig.spec.js.snap
test/__snapshots__/index.spec.js.snap
test/generateTasks.spec.js
test/getConfig.spec.js
test/resolveGitDir.spec.js
test/runScript-mock-findBin.spec.js
test/runScript.spec.js

remove gitDir config option

---

README.md

This adds a section to the readme documenting `lint-staged`'s support for multi package projects. Thanks to @awebdeveloper for suggesting it in #336.
Preview link - [/multi-pkg-prj/README.md@`docs`#how-to-use-lint-staged-in-a-multi-package-monorepo](https://github.com/okonet/lint-staged/blob/docs/multi-pkg-prj/README.md#how-to-use-lint-staged-in-a-multi-package-monorepo)
EDIT: ~~On hold till I can look into [typicode/husky:docs.md@`dev`#multi-package-repository-monorepo](https://github.com/typicode/husky/blob/dev/docs.md#multi-package-repository-monorepo)~~

docs(README): Document support for multi pkg projects

---

test/resolveGitDir.spec.js

This removes a duplicate test and adds a test for the case when `.git` dir is not in the project root.

test: Improve tests for resolveGitDir

---

README.md

Add section for minifying images with [imagemin-lint-staged][imagemin-lint-staged] to the `READEM.md`.
[imagemin-lint-staged]: https://github.com/tomchentw/imagemin-lint-staged

docs(README.md): add `imagemin-lint-staged` section

---

src/index.js
src/runAll.js
test/generateTasks.spec.js
test/runScript.spec.js

This removes some leftover code and config options in tests for `gitDir`.

refactor: Cleanup code and tests for gitDir

---

README.md
index.js
package.json
src/findBin.js
src/generateTasks.js
src/getConfig.js
src/index.js
src/runAll.js
src/runScript.js
test/__mocks__/my-config.json
test/__snapshots__/getConfig.spec.js.snap
test/__snapshots__/index.spec.js.snap
test/findBin.spec.js
test/getConfig.spec.js
test/index.spec.js
test/runScript.spec.js

This integrates [`debug`](https://github.com/visionmedia/debug) which can be enabled by setting the environment variable `$DEBUG` to `lint-staged*`. It can also be specified inline by doing the following:
```
$ DEBUG=lint-staged* git commit
λ set DEBUG=lint-staged* && git commit
```
Example output:
```
λ node . --debug
lint-staged:bin Running `lint-staged@0.0.0-development` +0ms
lint-staged Loading config using `cosmiconfig` +0ms
lint-staged Successfully loaded config from `E:\Projects\repos\lint-staged\.lintstagedrc`:
lint-staged { linters: { '*.js': [ 'eslint --fix', 'git add' ], '.*rc': 'jsonlint' } } +34ms
lint-staged:cfg Normalizing config +0ms
lint-staged:cfg Validating config +11ms
Running lint-staged with the following config:
{
linters: {
'*.js': [
'eslint --fix',
'git add'
], …
```

feat: Add debug logs

---

README.md

This adds a link to the releases to explicitly call out that it serves as our changelog.

docs(README): Add link to releases for changelog

---

package.json

for the sake of consistency, because we're using `yarn` now

chore(scripts): replace `npm run` with `yarn`

---

.travis.yml
appveyor.yml

To speed up CI builds,
we didn't do this before because we didn't commit lock files and wanted to run builds with fresh dependencies

ci: Cache dependencies

---

test/index.spec.js
test/printErrors.spec.js
test/runAll.spec.js
test/runScript-mock-findBin.spec.js
test/runScript-mock-pMap.spec.js
test/runScript.spec.js

To make sure certain numbers of assertions are called,
IMO this is important to give us more confidence in testing async codes.
We're using `expect.assertions()` already in:
https://github.com/okonet/lint-staged/blob/master/test/runAll.spec.js#L45
https://github.com/okonet/lint-staged/blob/master/test/runAll.spec.js#L66

test: Use `expect.assertions()` to test async codes

---

.travis.yml
appveyor.yml

in 2017, they have published 5 breaking changes 😰 
We need to update our `travis` config to make auto-publishing works again.
Edit: I think the most reasonable approach is to just install `semantic-release` as our devDependencies (like we did before)

ci(travis): Update `semantic-release` config

---

package.json
yarn.lock

Jest has dropped support for node 4, but that's because of `jsdom`, which you don't use.
~It would be preferable if you used lockfiles, as there's no guarantee that we'll keep support moving forward, but~ 22.0.4 works on node 4.
Closes #361, closes #362, closes #363, closes #364

chore(package): upgrade to jest 22

---

README.md

The 'Filtering files' section in the readme had not been updated when the `gitDir` option was deprecated in 5.0. This updates the section explaining the changes related to how files are resolved since `lint-staged@5`.
Preview link - [/README.md@`docs/filtering`#filtering-files](https://github.com/okonet/lint-staged/blob/docs/filtering/README.md#filtering-files)
Closes #373.

docs: Update inconsistent docs for filtering files

---

.travis.yml

v12 is now the `latest` version of `semantic-release`

ci(travis): Use `semantic-release` v12

---

README.md
src/generateTasks.js
src/getConfig.js
test/__snapshots__/getConfig.spec.js.snap
test/__snapshots__/index.spec.js.snap
test/generateTasks.spec.js
test/getConfig.spec.js

This allows users to prevent some files from being processed by lint-staged ever. This is useful if your project contains generated files that you commit to the repository, but don't want to process.
[I know it's not great to commit generated files](https://blog.kentcdodds.com/why-i-don-t-commit-generated-files-to-master-a4d76382564), but in this case it's really the best solution for me.
I didn't open an issue for this because I really need this anyway so if it's not merged then I'll just use my own fork.

feat(config): add `ignore` config option

---

README.md
package.json
src/generateTasks.js
yarn.lock

Since `micromatch` supports multiple filter patterns, this does the changes to filter staged files in a single pass for match and ignore patterns.
The following `minimatch` options are not supported in `micromatch`:
- `nocomment`: [isaacs/minimatch#`nocomment`](https://github.com/isaacs/minimatch#nocomment)
- `flipnegate`: [isaacs/minimatch#`flipnegate`](https://github.com/isaacs/minimatch#flipnegate)
So the change needs to go in a major release. The `next` branch, which this targets for the merge, will include multiple breaking changes and these will be released in a single major release.

perf: Switch from minimatch to micromatch

---

README.md
package.json
src/checkPkgScripts.js
src/findBin.js
src/index.js
src/runAll.js
src/runScript.js
test/__mocks__/npm-which.js
test/__snapshots__/checkPkgScripts.spec.js.snap
test/__snapshots__/findBin.spec.js.snap
test/checkPkgScripts.spec.js
test/findBin.spec.js
test/runAll.spec.js
test/runScript-mock-findBin.spec.js
test/runScript-mock-pMap.spec.js
test/runScript.spec.js
yarn.lock

This removes support for running scripts defined in package.json using `lint-staged`. The same can be done by specifying the command as `npm run script-name --`. This also adds a slight perf improvement for `findbin` by introducing simple caching to avoid repeatedly resolving binaries(ex: `git`).
Closes #376.

feat: Remove support for npm scripts

---

.babelrc
.eslintrc.json
.travis.yml
README.md
appveyor.yml
index.js
package.json
src/checkPkgScripts.js
src/findBin.js
src/generateTasks.js
src/getConfig.js
src/index.js
src/runAll.js
src/runScript.js
yarn.lock

This sets the minimum required  Node.js version to `>=6` and does the relevant config, code and docs update.
- Change Node.js requirement in `engines.node` to `>=6`. Use `please-upgrade-node` to give helpful error message on older versions.
- Remove node 4 from list of Node.js versions to test on CI. Also remove `--ignore-engines` flag for `yarn install`, not required with node 6.
- Add note to readme for Node.js version requirement.
- Target node 6 for `babel-preset-env` (relevant only for tests).
- Add eslint rule for `prefer-destructuring`, do relevant code changes.
- Use default argument for `logger` passed to `src/index.js`
Closes #372.

refactor: Drop support for Node.js 4

---

README.md

The "How to use `lint-staged` in a multi package monorepo?" section fits better under FAQ.

docs: Move section for use with monorepo under FAQ

---

src/printErrors.js
src/runScript.js
test/runScript.spec.js

This hides the error message in a private field to get around the duplicate logs issue. Most of the credit goes to @umarmw for the idea, so thank you!
Closes #142, #308, #406, #415.

fix: Hide err msg in private field to avoid duplicate logs

---

package.json
src/findBin.js
test/findBin.spec.js
yarn.lock

Switched to `string-argv` since `cli-command-parser` seems to have a bug.
Closes #419 
Note to self: next time listen to @sudo-suhas 🤦‍♂️

fix: Parse arguments with single quotes properly. Better tests.

---

package.json
yarn.lock

Includes semantic version range checking that avoids incorrect flagging of Node.js version 10+. https://github.com/typicode/please-upgrade-node/issues/11
Resolves #432
Edit: Closes #433

fix: update "please-upgrade-node" to version 3.0.2

---

src/index.js

The "support-color" package expects to parse an integer value. Code was wrongly assigning a boolean
when envvars are strings. Don't see how this ever worked. Additionally removed line setting
`process.exitCode` to its default value (`0`), and migrated `process.exitCode = 1` to top of both catch blocks.
Fixes #448

448: Correct value for FORCE_COLOR env var

---

README.md
__mocks__/my-lint-staged-config/index.js
__mocks__/my-lint-staged-config/package.json
src/index.js
test/__snapshots__/index.spec.js.snap
test/index.spec.js

feat: Resolve a npm package passed as `--config`
This PR enables a npm package to be passed to the command line `--config` parameter and will be resolved by lint-staged.
Example:
Say you have a npm package `my-tools-config/lint-staged`, your application can now depend on the configuration package and lint-staged allowing:
```sh
lint-staged --config my-tools-config/lint-staged
```

feat: Resolve a npm package passed as `--config`

---

README.md
src/generateTasks.js
test/generateTasks.spec.js

Files are not filtered only when pattern starts with `../`. This avoids adding another flag to the config and should work as expected for existing users.
Closes #425.
Closes #487.
Closes #492.

feat: Allow linting files outside of project folder

---

README.md

Hi 👋 
I've just released husky `1.0` (it was behind a flag for the past months). This PR updates examples to match the new way to add hooks. It also solves the issue with commitizen 👍

docs: Update documentation for husky 1.0

---

package.json
yarn.lock

Since you don't support node 4, it's safe to upgrade 🙂 
Using Jest 23 means that you can use e.g. https://github.com/jest-community/jest-watch-typeahead if you want

chore: upgrade to jest 23

---

src/gitWorkflow.js
test/gitWorkflow.spec.js

When options aren't specified, instead of using `process.cwd()`
use `resolveGitDir()`.
Fixes #514

fix(git): Use resolveGitDir to resolve to .git for git commands

---

README.md

Revised the following points:
- Added `stylelint --fix` on "Reformatting the code" section
- Simplified `prettier` calls since it can infer parser type from the file extension
- Added `prettier` example on Markdown and HTML files

docs(readme): refine prettier examples

---

README.md
src/generateTasks.js
src/getConfig.js
test/__snapshots__/getConfig.spec.js.snap
test/__snapshots__/index.spec.js.snap
test/generateTasks.spec.js
test/getConfig.spec.js

In order to work with the new version of [angular-cli](https://github.com/angular/angular-cli) which is now using `--files` parameter to pass specific RELATIVE file paths to lint ([see here](https://angular.io/cli/lint)) I wasn't able to let my project working with lint-staged. I think I'm not the only one in this situation.
Signed-off-by: Benjamin Coenen <benjamin.coenen@corp.ovh.com>

feat: add relative option to let lint-staged work with ng lint

---

.travis.yml

Should fix https://github.com/okonet/lint-staged/issues/546 and https://github.com/semantic-release/semantic-release/issues/539 where links in releases section were using git+https protocol.

Chore: Upgrade semantic-release to latest

---

test/gitStash.spec.js

Developers have to keep `jest.dontMock('execa')` on the top as the comment says. If someone move it to somewhere else, test will fail. This PR makes it more robust.

feature: use unmock to avoid explicit hoist

---

README.md

I found this example in #358, which works great!

docs(readme): Add example for environment variables

---

package.json
src/getConfig.js
test/__snapshots__/getConfig.spec.js.snap
test/getConfig.spec.js
yarn.lock

Fixes #567 
This pull request introduces a custom validator that replaces `jest-validate`
Improvements over the previous implementations are: 
- You can now set a function as a renderer
- Validations can be more precise
- Linters are validated (check that key is a glob, and that values are a string or array of strings)
- valid values for `renderer` are now explicit, where any string was possible before
- Check that `ignore` is an array of strings
I tried to use `joy` `yup` and `schema-utils` to express the schema to validate, but it felt more verbose and less flexible with regard to the number of possible options.
I just ensured that current tests pass, I can write more tests if needed.

Improve configuration validation

---

src/runAll.js
test/__snapshots__/runAll.spec.js.snap
test/runAll.spec.js

- add check for lint-staged files before stashing changes
- add test to check if stashing is skipped if no lint-staged files are changed
Fixes #570

Avoid stashing if no lint-staged files are changed (#570)

---

package.json
yarn.lock

The lodash version in lint-staged is vulnerable to prototype pollution. 
https://nodesecurity.io/advisories/782
This PR just updates the lodash version.

chore: update lodash version

---

package.json
yarn.lock

Seems to be an issue with listr-update-renderer, version 0.5.0 was
released more recent not scoped.
Closes #585
Original: https://www.npmjs.com/package/@iamstarkov/listr-update-renderer
Updated: https://www.npmjs.com/package/listr-update-renderer

fix: fix issue with scoped pkg listr-update-renderer

---

package.json
yarn.lock

Update yup to 0.27.0, prevent @babel/runtime strict version pinning.
See https://github.com/jquense/yup/issues/486

fix: prevent @babel/runtime strict version pinning

---

README.md

```Node
> const micromatch = require('micromatch');
> console.log(micromatch(['foo/bar.js', 'baz.js'], ['*.js']))
[ 'baz.js' ]
> console.log(micromatch(['foo/bar.js', 'baz.js'], ['*.js', '**/*.js']))
[ 'baz.js', 'foo/bar.js' ]
> console.log(micromatch(['foo/bar.js', 'baz.js'], ['**/*.js']))
[ 'foo/bar.js', 'baz.js' ]
```

Update README wrt filtering files

---

package.json
yarn.lock

As discussed in #600, `js-yaml` has a high-level security vulnerability, and `cosmiconfig` depends on it. In this PR, I bump up the version of `cosmiconfig` to 5.2.0 (which should introduce no breaking changes), and regenerate the `yarn.lock` file. Now, running `yarn audit` no longer yields any high severity security errors (though there is one moderate found in `lodash`, and many low-level security vulnerabilities as children of `jest`). 
Please let me know if there's anything else I should do!

Resolves [High] Security Vulnerability in js-yaml

---

README.md

docs: update husky post-commit configuration

---

README.md
package.json
src/execGit.js
src/generateTasks.js
src/gitWorkflow.js
src/makeCmdTasks.js
src/resolveGitDir.js
src/runAll.js
test/__snapshots__/runAll.2.spec.js.snap
test/__snapshots__/runAll.spec.js.snap
test/generateTasks.spec.js
test/index.spec.js
test/makeCmdTasks.spec.js
test/resolveGitDir.spec.js
test/resolveTaskFn.spec.js
test/runAll.2.spec.js
test/runAll.spec.js
yarn.lock

This pull reguest refactors the `resolveGitDir` to run `git rev-parse --show-toplevel`. It also calculates this only once in the `runAll` method, passing it down to the `gitWorkflow`, `makeCmdTasks` and `generateTasks` methods.
~~Additionally, when `config.relative === true`, the the `cwd` where all `git` commands are run is the actual `process.cwd()` (location of `package.lock`), instead of the `gitDir`. This significantly speeds up the `stash`/`pop` workflow of partial file commits in large monorepos. In our case, the runtime of the initial stash goes down to 400 ms from over 5 seconds.~~ This will be moved to a separate PR.
What do you think?

Generate gitDir only once, using `git rev-parse --show-toplevel`

---

src/resolveGitDir.js
test/resolveGitDir.spec.js

A potential, but slightly more hacky, fix for https://github.com/okonet/lint-staged/issues/627

overriding env variable to find git dir

---

.lintstagedrc.json
package.json
src/getStagedFiles.js
src/runAll.js
test/__snapshots__/runAll.spec.js.snap
test/getStagedFiles.spec.js
test/gitStash.spec.js
test/runAll.spec.js
yarn.lock

This pull request removes the `staged-git-files` and `pify` dependencies and uses the internal `execGit` to list staged files. This is done via
```bash
git diff --staged --diff-filter=ACM --name-only
```
This should be the same behaviour as `staged-git-files, since only the filenames were used.

refactor: use internal execGit to list staged files

---

.appveyor.yml
.travis.yml
index.js

PR adds the lowest required node version to ~~_package.json_'s `engines.node`~~ to the bin entrypoint. The requirement currently comes from [execa](https://github.com/sindresorhus/execa/blob/master/package.json).
It also updates the CI environments to test with node versions `8`, `10` and `12`, because version 9 isn't really supported.
Replaces PR https://github.com/okonet/lint-staged/pull/525 as stale.

Update node version requirement

---

README.md
src/makeCmdTasks.js
src/resolveTaskFn.js
test/makeCmdTasks.spec.js
test/resolveTaskFn.spec.js
test/resolveTaskFn.unmocked.spec.js

Function linters have to be evaluated at makeCmdTasks, and resolveTaskFn has to run for each of the returned commands.
Currently, `makeCmdTasks` creates only a single task per function linter, and `resolveTaskFn` returns an array of promises. This PR fixes the logic by evaluating functions at `makeCmdTasks` level, and running `resolveTaskFn` for each of the commands returned, simplifying `resolveTaskFn`.
This PR fixes issues where a function linter returning an array of commands might only run the first of the commands.

fix: run all commands returned by function linters

---

README.md
bin/lint-staged
package.json
src/index.js
src/makeCmdTasks.js
src/printErrors.js
src/resolveTaskFn.js
src/runAll.js
test/__snapshots__/index.spec.js.snap
test/__snapshots__/runAll.spec.js.snap
test/index.spec.js
test/index2.spec.js
test/printErrors.spec.js
test/runAll.spec.js

We have a use-case where we need to call `lint-staged` from inside another node script (there are other pre-commit steps that need to run). Currently we're calling out to `lint-staged` via `execa` but it's slower than calling it in-process via an exposed node API.

feat: make node-api accessible

---

src/generateTasks.js
src/runAll.js
test/__snapshots__/runAll.unmocked.spec.js.snap
test/runAll.unmocked.spec.js

This PR adds a full 8-scenario integration test for `runAll`:
1. Should commit entire staged file when no errors from linter
1. Should commit entire staged file when no errors and linter modifies file
1. Should fail to commit entire staged file when errors from linter
1. Should fail to commit entire staged file when errors from linter and linter modifies files
1. Should commit partial change from partially staged file when no errors from linter
1. Should commit partial change from partially staged file when no errors from linter and linter modifies file
1. Should fail to commit partial change from partially staged file when errors from linter
1. Should fail to commit partial change from partially staged file when errors from linter and linter modifies files
Scenarios taken from here: …

Add integration test

---

src/runAll.js
test/__snapshots__/runAll.spec.js.snap

In the console output `lint-staged` mostly refers to "tasks" (examples: [1](https://github.com/okonet/lint-staged/blob/master/src/runAll.js#L69), [2](https://github.com/okonet/lint-staged/blob/28da59a975da367b3ca9710e5387049c29fb1467/src/runAll.js#L95)) but in this line it refers to "linters" ([source](https://github.com/okonet/lint-staged/blob/28da59a975da367b3ca9710e5387049c29fb1467/src/runAll.js#L118)). I've found `lint-staged` to be incredibly useful beyond just linting, so I was hoping we could change them to "tasks" to be consistent?

refactor: change "Running linters..." to "Running tasks..."

---

test/runAll.unmocked.spec.js

This PR adds two tests.
1. There is a staged file that does not pass prettier’s formatting
1. There are unstaged modifications that properly prettify the file
1. `lint-staged` runs `prettier --fix` and `git add` to essentially do the same thing as the unstaged modifications
The result:
1. `lint-staged` succesfully fixed and committed the file
1. The unstaged modifications are gone, since they’re already in place
1. There is a staged file that does not pass prettier’s formatting
1. There are further unstaged changes in the same file
1. `lint-staged` runs `prettier --fix` and `git add`, but also create a `.git/index.lock` file, failing git operations (like the `git add`)
The result:
1. `lint-staged` fails to create a new commit
1. `git status` matches the status before committing, but …

Add more tests

---

src/gitWorkflow.js

I just happened to stumble upon this minor logic issue, and fixed it. Because the template string `patch` always has a newline appended to the `diff`, it will always be thruthy and thus the patch will get applied every time. Here's a test case:
```js
const diff = ''
const patch = `${diff}\n`
if (patch) {
console.log('We have a patch!')
}
// We have a patch!
```
Why everything has worked previously, I assume, is that when applying the patch fails, it is caught via the removal of `.ref` files, which itself is caught.
For reference, applying a newline fails:
```bash
❯ echo '\n' | git apply -v --reject --whitespace=nowarn --recount --unidiff-zero -
error: unrecognized input
```
This PR changes the check of applying a patch to the `diff` itself, and then adds the newline during execa's input.

fix: apply patch only if there's a diff

---

package.json
src/execGit.js
src/generateTasks.js
src/resolveGitDir.js
src/runAll.js
test/generateTasks.spec.js
test/gitWorkflow.spec.js
test/resolveGitDir.spec.js
test/runAll.spec.js
yarn.lock

This PR adds the [normalize-path](https://github.com/jonschlinkert/normalize-path) module for always converting file paths to unix-like forward slashes. It also fixes a bug in `generateTasks` where absolute paths were resolved incorrectly when the working directory is a sub directory of the git repository.

fix: always use unix slashes in paths and correctly handle ../ globs

---

src/getStagedFiles.js

This PR adds the `R` to diff-filter when getting list of staged files, for when git decides a file has been renamed. Fixes https://github.com/okonet/lint-staged/issues/683.
Should we add a new test for renames, @okonet? It seems everything is working fine, but if you had doubts about it causing issues, maybe a test would be nice.

fix: include renames when getting list of staged files

---

src/validateConfig.js
test/__snapshots__/validateConfig.spec.js.snap
test/validateConfig.spec.js

This PR adds more precise validation of function tasks, which should be of the form `(filenames: string[]) => string | string[]`. Specifically, the return value is validated by supplying the task with an array of single filename `['[filename]']`.

fix: validateConfig validates function task return values

---

README.md
src/index.js

It would be very useful if someone wants to use lint-staged as library (me)

Allow to pass config instead of configPath

---

src/makeCmdTasks.js
src/resolveTaskFn.js
src/runAll.js
test/makeCmdTasks.spec.js
test/resolveTaskFn.spec.js
test/resolveTaskFn.unmocked.spec.js
test/runAll.unmocked.spec.js

This PR makes function task titles shorter by omitting the full list of staged filenames, instead passing them a single `[file]` as the argument. This means the task still shows the expected function, but is shorter; for example `eslint --fix [file] && git add [file]`.
The mechanism of creating the title is a bit complex, since we need to first create as long an array of `[file]` strings and evaluate the function task against it. This makes sure the output is the same as for the actual file list. After this, from a single command string multiple `[file]` entries are truncated into one, so for example `ng lint --file [file] --file [file] --file [file]` turns into `ng lint --file [file]`.
I also refactored away usages of `linter` to more generic `task` and `command`.
Fixes …

Create shorter title for function tasks with many staged files

---

README.md

This PR adds a bit about testing `lint-staged@next` to the README. Ping @okonet.

fix: add note about next version

---

src/makeCmdTasks.js

I made a mistake on https://github.com/okonet/lint-staged/pull/706 where the title for function tasks is generated by creating a mock array of filenames with the length of the matched functions, when it instead should be the the length of the staged files array. This causes failures with function linters in some situations.
Should fix the problem reported by @VitorLuizC in https://github.com/okonet/lint-staged/pull/706#issuecomment-538075240.

fix: create fn title with mock file list of correct length

---

.travis.yml

This PR should enable pre-release channels as documented in https://github.com/semantic-release/semantic-release/blob/beta/docs/recipes/pre-releases.md#publishing-pre-releases

build: Use semantic-release@16.0.0-beta to enable prerelease channels

---

README.md

In the README, an example is given for how to match only files in the root directory of the repository.  One crucial character is missing, however, preventing the example from working.  Specifically, the example needs to begin with `./` (not just `/`) in order to be interpreted as a relative path but not to trigger setting micromatch's `matchBase` option.  Without that dot, the path is interpreted as an absolute one and fails to match as a relative path.

Fix root-dir-only example

---

README.md
bin/lint-staged
lib/chunkFiles.js
lib/index.js
lib/runAll.js
test/__snapshots__/runAll.spec.js.snap
test/chunkFiles.spec.js
test/runAll.spec.js
test/runAll.unmocked.spec.js

This PR adds chunking to running tasks to better support Windows shells with more limited maximum argument string length.
The logic of chunking is to first create the full argument string `filesArg` by joining the list of staged files (and resolving as absolute paths when necessary). This string's length is compared to a safe value of half of the maximum argument length `maxLength`, and the number of chunks is calculated as `Math.min(Math.ceil(filesArg/maxLength), files.length)`. So when the `filesArg` is for example 3.5 times the length of `maxLength`, four chunks are created. If there for whatever reason are less files than chunks, at most one file per chunk is created.
After chunking, instead of a single `Running tasks...`, there will be `Running tasks (1/4)...` and so on.
Fixes …

feat: split tasks into chunks to support shells with limited max argument length

---

README.md

This adds an example on dealing with eslint ignored files, to fix the issues with `warning  File ignored because of a matching ignore pattern. Use "--no-ignore" to override` errors blocking commits.

Update README on dealing with eslintignore

---

package.json

This PR adds the npm funding property, which will show a notification when using `npm install`. It also enables the `npm fund lint-staged` command, opening the Open Collective link in the default browser.

docs: add funding property to package.json linking to Open Collective

---

README.md
bin/lint-staged
lib/gitWorkflow.js
lib/index.js
lib/runAll.js
test/runAll.unmocked.spec.js

BREAKING CHANGE: Previously, lint-staged would allow empty commits in the situation where a linter task like "prettier --write" reverts all staged changes automatically. Now the default behaviour is to throw an error with a helpful warning message. The --allow empty option can be used to allow empty commits, or `allowEmpty: true` for the Node.js API.
What do you think, @okonet?

feat: throw error to prevent empty commits unless --allow-empty is used

---

README.md

Fixes  #764; clarifies the purpose of switching to the `listr-verbose-renderer` module.

Improve documentation on the --debug flag

---

.eslintrc.json
lib/file.js
lib/gitWorkflow.js
lib/runAll.js
test/__snapshots__/runAll.spec.js.snap
test/gitWorkflow.spec.js
test/runAll.unmocked.spec.js

This PR adds missing error handling to the untracked files restoration, and uses the same diff arguments as for the unstaged diff.
These omissions when combined possibly lead to new untracked files getting lost when running _lint-staged_. The test didn't detect this because one reason might be the missing `--binary` flag.
~~The test coverage dropped significantly because now when the backup stash is missing, `runAll` fails earlier. Not sure how to test the last error handler at this point.~~
Fixes https://github.com/okonet/lint-staged/issues/779

Fix untracked file handling

---

bin/lint-staged
bin/lint-staged.js
lib/runAll.js
package.json

This PR adds detection for the `TERM=dumb` env variable and sets cli-output to use the verbose renderer, instead of the default dynamic one.
Fixes https://github.com/okonet/lint-staged/issues/781

fix: use verbose renderer when TERM=dumb

---

lib/resolveGitRepo.js
lib/runAll.js
test/runAll.unmocked.spec.js

This PR fixes https://github.com/okonet/lint-staged/issues/783 by always checking if the the `.git` directory is actually file, and then resolves the real directory location by reading the file.
This works for both submodules and added worktrees.

fix: always resolve real git config dir location if .git is a file

---

lib/file.js
lib/getStagedFiles.js
lib/gitWorkflow.js
lib/index.js
lib/resolveGitRepo.js
test/file.spec.js
test/gitWorkflow.spec.js
test/runAll.unmocked.2.spec.js
test/runAll.unmocked.spec.js

Fixes https://github.com/okonet/lint-staged/issues/561
Currently, version 10 only fixes some of the issues with deleted files getting restored when running lint-staged. This PR adds yet more checks to fix the remaining issues. The issue itself seems to be with the way git tracks files, and you can read more [here in Stack Overflow](https://stackoverflow.com/questions/48446845/git-stash-restoring-index-state-of-deleted-and-renamed-files).
I also updated some eslint rules to take into account the Node.js version bump, and after that refactored the file api to use `fs.promises` to simplify the code.

fix: make sure deleted files aren't restored due to git bugs

---

lib/file.js
lib/resolveGitRepo.js

This PR fixes https://github.com/okonet/lint-staged/issues/785 by removing usages of `fs.promises` and instead wrapping the older individual callback methods of `fs` with `util.promisify`.
Apparently the Node.js LTS 10.X docs state that `fs.promises` is stable, but the _ExperimentalWarning_ has only been removed in v12.

fix: replace fs.promises with util.promisify to suppress ExperimentalWarning on Node.js v10

---

lib/resolveGitRepo.js

Replace `path.resolve` with `path.join` for better behavior with paths in msys, and normalized the path also for better behavior in msys.

normalize joined defaultDir path when resolving git config dir

---

lib/getStagedFiles.js
test/getStagedFiles.spec.js
test/runAll.unmocked.spec.js

Support files with non-ASCII file names when git is configured with core.quotepath on

---

README.md
bin/lint-staged.js
lib/file.js
lib/gitWorkflow.js
lib/index.js
lib/resolveGitRepo.js
lib/runAll.js
test/__mocks__/gitWorkflow.js
test/__snapshots__/runAll.spec.js.snap
test/gitWorkflow.spec.js
test/runAll.spec.js
test/runAll.unmocked.2.spec.js
test/runAll.unmocked.spec.js

This PR optimizes the git workflow by only doing the complex `git diff`/`git apply` to files with both unstaged and staged changes, a bit like it was with v9.
The backup stash created in the first step is applied right back, removing the need to dig untracked changes from the stash's third commit. This also means that unstaged changes are around for the tasks (like edits to eslint configuration), fixing troubles in issue https://github.com/okonet/lint-staged/issues/794. Also, a diff of unstaged changes is saved in a simpler way by running `git diff` before stashing (without the `--index` flag it includes unstaged changes).
Any unstaged changes to files that also have staged changes are cleaned out using `git checkout <file>`. After tasks have run, the diff from unstaged changes will be …

feat: use diff/apply only with partially staged files

---

lib/gitWorkflow.js
test/runAll.unmocked.spec.js

Without the -- denoter some paths might be interpreted as flags.
Fixes https://github.com/okonet/lint-staged/issues/820

fix: add `--` to `git add` command to denote pathspec starting

---

lib/gitWorkflow.js
lib/runAll.js
test/runAll.unmocked.2.spec.js
test/runAll.unmocked.spec.js

Since v10.1 having untracked files in the backup stash causes revert to fail, because the stash will not apply with the same files already on disk.
Fixes https://github.com/okonet/lint-staged/issues/826

fix: no longer include untracked files in backup stash

---

lib/chunkFiles.js
lib/gitWorkflow.js
lib/runAll.js
test/chunkFiles.spec.js

This prevents race conditions with `git add` locking the repository. This mostly affects Windows users because on other platforms there is typically only one chunk.
Fixes https://github.com/okonet/lint-staged/issues/836

fix: run `git add` for staged file chunks serially

---

lib/gitWorkflow.js
test/gitWorkflow.spec.js
test/runAll.spec.js
test/runAll.unmocked.2.spec.js
test/runAll.unmocked.spec.js

The `git stash create` command creates a dangling stash commit without removing any files from the disk, and returns its hash. This when passed to the `git stash store` commit saves it as a regular stash.
What follows is that the files never leave disk, and so don't trigger any side-effects with file watchers or other processes that might be running when lint-staged is running.
Fixes https://github.com/okonet/lint-staged/issues/844

fix: use stash create/store to prevent files from disappearing from disk

---

lib/chunkFiles.js
lib/gitWorkflow.js
lib/runAll.js
test/chunkFiles.spec.js
test/runAll.spec.js

Because the set of matched files are collected from generated tasks, when using the `relative` options they are relative to the current cwd, not the git dir which might be different.

fix: resolve matched files to cwd instead of gitDir before adding

---

lib/chunkFiles.js
test/chunkFiles.spec.js

The previous PR https://github.com/okonet/lint-staged/pull/857 only fixed the situation when `maxArgLength` was not set (when used throught the Node.js API).

fix: chunkFiles chunks normalized files even when maxArgLength is set

---

package.json
yarn.lock

About the issue https://github.com/cenk1cenk2/listr2/issues/25 of listr2 with the problems of UUID when used with Node 13.x. Rollback should fix it.
Related issues in the base library: https://github.com/uuidjs/uuid/issues/428

fix: node-13 deps issue with listr2 and uuid

---

lib/makeCmdTasks.js
lib/runAll.js
package.json
test/index.spec.js
test/integration.test.js
test/makeCmdTasks.spec.js
test/utils/replaceSerializer.js
yarn.lock

This makes sure the task title is as long as possible to fit on a single line of the console output, applying both to regular and functional tasks.

fix: truncate command title to stdout width

---

package.json
test/gitWorkflow.spec.js
test/integration.test.js
test/utils/tempDir.js
yarn.lock

nanoid contains conditional exports and emits a warning on Node.js >= 13.7: `ExperimentalWarning: Conditional exports is an experimental feature. This feature could change at any time`.
Fixes https://github.com/okonet/lint-staged/issues/872

fix: remove nanoid devDependency to remove ExperimentalWarning

---

lib/gitWorkflow.js
test/gitWorkflow.spec.js

When a partially staged file name contains one or more spaces or special characters, `git status --porcelain` escapes and quotes the file name (see https://github.com/okonet/lint-staged/blob/master/lib/gitWorkflow.js#L161). Consequently, `gitWorkflow.hideUnstagedChanges()` fails with a pathspec error since `execa` expects arguments to not be escaped or quoted:
```
[SUCCESS] Preparing...
[STARTED] Hiding unstaged changes to partially staged files...
[FAILED] error: pathspec '"src/file with spaces.ts"' did not match any file(s) known to git
✖ lint-staged failed due to a git error.
Any lost modifications can be restored from a git stash:
> git stash list
stash@{0}: automatic lint-staged backup
> git stash apply --index stash@{0}
```
This PR resolves the problem by using the machine output …

Use machine output for listing partially staged files

---

lib/runAll.js
test/index2.spec.js

When replacing listr with listr2, this was a change in default behaviour that was left unnoticed
Fixes https://github.com/okonet/lint-staged/issues/880

fix: canceling lint-staged via SIGINT restores state and cleans up

---

package.json
yarn.lock

Enquirer became a peer dependency of Listr2 here: https://github.com/cenk1cenk2/listr2/commit/cae55e962faf54f3ddadc6c220567a316c8ee15b
This should be added, so that repositories including lint-staged won't see the message
```
npm WARN listr2@2.1.0 requires a peer of enquirer@>= 2.3.0 < 3 but none is installed. You must install peer dependencies yourself.
```

fix: Add enquirer peer dependency

---

lib/resolveGitRepo.js
test/resolveGitRepo.spec.js

Resolving the git directory failed if the environment variable `GIT_WORK_TREE` is set to a relative path and lint-staged is run from a subdirectory of a Git repository (e.g. multi-package repos).
`GIT_WORK_TREE` can be used to set the worktree directory for a Git repo. `GIT_DIR` specifies only the `.git` directory path. `git rev-parse --show-toplevel` will return the Git worktree directory. If it is set to a relative path, it won't work when git commands are called from a subdirectory, as the relative path will fail to resolve correctly.
While `GIT_DIR` is unset in `resolveGitRepo.js`, `GIT_WORK_TREE` was not. Unsetting `GIT_WORK_TREE` in the same place fixes the issue.
Resolves #886

fix: Git directory is not resolved if GIT_WORK_TREE is set to relative path

---

lib/execGit.js
test/execGit.spec.js

This explicitly prevents git commands from recursing into git submodules and thus causing issues with commands like stash or reset.
Fixes https://github.com/okonet/lint-staged/issues/884

fix: run all git commands with submodule.recurse=false

---

README.md

**Fix:** `micromatch` treats path strings differently, so `*.js` matches only those js files which are in drive's root, given the config function gets array of _absolute_ paths as parameter. This PR fixes that.
**Enhance:** This PR also adds more clarification to the example by showing how multiple commands can be executed on different types of staged files.

docs: fix & enhance "Use your own globs" example

---

README.md
lib/formatConfig.js
lib/index.js
test/__snapshots__/validateConfig.spec.js.snap
test/formatConfig.spec.js
test/validateConfig.spec.js

This PR adds an ability to use a function as config. This function will get an array of all staged files as parameter which can be used with own globs. Currently, we need to pass such function as value of `'*'` in config object which doesn't feel good.
This can be further optimized by not using `micromatch` internally when a function config is detected.

feat: add ability to use function as config

---

lib/index.js

[cosmiconfig v7](https://github.com/davidtheclark/cosmiconfig/blob/master/CHANGELOG.md#700) added support for `.cjs` config files. This is useful in scenarios where the package is using es6 modules (e.g. package.json [`type` parameter is set to `module`](https://nodejs.org/api/esm.html#esm_package_json_type_field)) but the config files are still in common js. Unfortionaltly, a config file ending with `.cjs` is not current supported:
```shell
lint-staged.config.cjs
lint-staged:bin Running `lint-staged@10.2.13` +0ms
lint-staged:bin Options parsed from command-line: {
allowEmpty: false,
concurrent: true,
configPath: undefined,
debug: true,
maxArgLength: 131072,
stash: true,
quiet: false,
relative: false,
shell: false,
verbose: false
} +1ms
lint-staged Loading config using `cosmiconfig` +0ms …
```

Add support for .cjs configs

---

README.md
lib/index.js

This adds support for common js files using the ES Module interop spec.
This is for projects who have `"type": "module"` in their `package.json`, normal `.js` files fail to load saying that you need to use import. `json` and `yaml` work just fine, but in the cases like with `typescript` where you need to run `tsc` without passing in file parameters, the only way to do that is with the `.js` files.
Using the `.cjs` extension forces it to load as a common js file and works correctly even in es-module enabled projects.
I'm also happy to update the documentation, but the documentation didn't refer to the other possible extensions mentioned in this file, so I'll wait until I hear back.

Update docs on supported file extensions

---

README.md
bin/lint-staged.js
lib/messages.js

Went back and forth on whether to put the functionality in `bin/lint-staged.js` or `lib/index.js`. Decided on `bin/lint-staged.js` since it doesn't make full sense to include in the programmatic API since the library user can read the config from wherever they'd like and provide it as an object.

feat: read config from stdin

---

README.md

This effectively removes political references.
Closes #931
---
The link to Ben McCormick's blog post is left as is (title, title-case) in an effort to minimize disruption there.  Sentence-case is used for the others as a subtle indicator of being a description and not a title.  Author(s) and date are added to all for the sake of consistency.

docs: use bibliography-style links in related posts section of readme

---

lib/index.js
test/__snapshots__/index2.spec.js.snap
test/index2.spec.js

Added tests for the original PR https://github.com/okonet/lint-staged/pull/915

better logging for js config errors

---

README.md

docs: add instructions for async ESLint isPathIgnored

---

README.md

This PR adds a link to my blog post that details how to use the wonderful `lint-staged` to consistently format your C#.
https://blog.johnnyreilly.com/2020/12/prettier-your-csharp-with-dotnet-format-and-lint-staged.html
Thanks so much for `lint-staged` by the way, it's an invaluable tool!

Add link to CSharp / lint-staged integration blog

---

README.md

Might be too much for the readme so feel free to close, but it's a snippet of code I wrote to automatically run all extensions prettier supports through prettier without having to keep a static list of extensions up to date.

add snippet to readme to run prettier for all supported files

---

bin/lint-staged.js

Hello.
The value of `--concurrent` CLI option is passed as string like `'true'` and `'2'`.
And tasks run serially when this option is set (even `--concurrent true`).
This is because the code to assign concurrency looks like this.
```ts
// node_modules/listr2/dist/listr.js:34-40 
this.concurrency = 1;
if (this.options.concurrent === true) {
this.concurrency = Infinity;
}
else if (typeof this.options.concurrent === 'number') {
this.concurrency = this.options.concurrent;
}
```
I have fixed this behavior.
Please review this PR, thanks.
before → after.

fix: concurrent option is not working correctly

---

README.md

`mrm` [recently migrarted](https://github.com/sapegin/mrm/pull/149) from `husky` to [`simple-git-hooks`](https://github.com/toplenboren/simple-git-hooks). I updated the text according to these changes.
This `mrm` migration brought  these benefits to users:
* `simple-git-hooks` has 0 dependencies and took 10 KB of `node_modules` space compared to 1 MB of husky 4.
* `simple-git-hooks` doesn’t read config on every `pre-commit` hook call which increases the performance. It uses the husky 5 model when you need explicitly to call a script on config changes. But it is a good trade-off for `lint-staged` case. It should give around a 0.5 second performance boost for `pre-commit`.
Comparison with husky 5:
1. We can start having all husky 5 benefits (performance, small size) without waiting for MIT …

Husky to simple-git-hooks migration in mrm

---

README.md

I forgot to change these section in my previous PR

Use simple-git-hooks in examples

---

README.md

Husky 6 has been released and is MIT. It's only 6 kB now with the same main features as husky 4.
`mrm-lint-staged-task` has been updated too.

docs: update installation and examples

---

README.md
bin/lint-staged.js

This fixes a bug introduced in #994 where any text after the `--shell` option was interpreted as its value, for example in `--shell  --relative` the value was `"--relative"` instead of implied `true`.

fix: the shell option value should be optional instead of required

---

README.md

Simplify configuration example by replacing script with [Prettier's `--ignore-unknown` flag](https://prettier.io/docs/en/cli.html#--ignore-unknown).

Simplify configuration example for formatting any format Prettier supports

---

README.md

The README advised ESLint >= 7 users to install node-filter-async. Replace this suggestion with a simpler implementation requiring the same number of lines of code but no dependencies. Rename the variable `eslintCli` to `eslint` since it is an instance of the ESLint Node.js API as distinct from the ESLint CLI. Avoid instantiating the API when the files staged don't necessitate invocation of ESLint.

Simplify Ignoring Files From .eslintignore.

---

.husky/pre-commit
README.md

This ensures the shell scripts work across different UNIX operating system: https://en.wikipedia.org/wiki/Shebang_(Unix)#Program_location
For example, I'm using NixOS and unfortunately `sh` is not located at `/bin/sh`

Use /usr/bin/env sh instead of direct path

---

bin/lint-staged.js

I think the current code is reading package.json from the current working directory.
If the package.json did not have a version number, it would cause lint-staged to crash.

fix: read version number from lint-staged package.json (#1043)

---

README.md
lib/index.js
lib/loadConfig.js
lib/symbols.js
lib/validateConfig.js
package-lock.json
package.json
test/__mocks__/cosmiconfig.js
test/__mocks__/lilconfig.js
test/__snapshots__/validateConfig.spec.js.snap
test/index.spec.js
test/integration.test.js

This PR revives https://github.com/okonet/lint-staged/pull/981 by replacing [`cosmiconfig`](https://github.com/davidtheclark/cosmiconfig) with [`lilconfig`](https://github.com/antonk52/lilconfig) + [`yaml`](https://github.com/eemeli/yaml) to reduce the number and size of dependencies used by _lint-staged_. The first PR introduced some problems (https://github.com/okonet/lint-staged/pull/1033) and was later reverted (https://github.com/okonet/lint-staged/pull/1035).
It seems `lilconfig` doesn't support loading configurations from a module, so that functionality was added as well.
This draft will be left for later...

feat: replace `cosmiconfig` with `lilconfig` + `yaml` to reduce dependencies

---

README.md
package-lock.json
package.json

This package is a peer dependency of `listr2`, but it's not used by _lint-staged_. Fixes https://github.com/okonet/lint-staged/issues/1048.

fix: install `enquirer`

---

lib/loadConfig.js

This PR fixes a regression introduced in [v12.1.0](https://github.com/okonet/lint-staged/releases/tag/v12.1.0) that breaks JS configuration loading. For some reason the tests pass, I assume this is because the code gets transpiled with Babel.

fix: await for dynamic import promise when loading JS config

---

package-lock.json
package.json

The `enquirer` dependency is unused by _lint-staged_, because we don't use interactive prompts. Previously it was removed but then restored because of an "unmet peer dependency warning", see https://github.com/okonet/lint-staged/pull/1050 and https://github.com/okonet/lint-staged/issues/1048.
Now [enquirer@3.13.4](https://github.com/cenk1cenk2/listr2/releases/tag/v3.13.4) has marked it as an optional peer dependency, so the warning is no longer emitted (see https://github.com/cenk1cenk2/listr2/issues/589), so we can safely remove it again.

fix(deps): remove enquirer because it's now optional by listr2

---

lib/resolveGitRepo.js

I've found this issue when executing lintStaged from node v16. My current setup is as follows:
I have 2 different folders:
- `/path/to/project/git` => root folder of the git repository
- `/path/to/project` => root folder for the project, which is NOT a git repository
When executing lintStaged, the setup is as follows:
- Node JS process is executed with `process.cwd() == /path/to/project`
- Inside the JS file executed by Node, I call  `lintStaged({ cwd: '/path/to/project/git'})`
- I get the `Current directory is not a git directory!` error
After debugging the code, the issue seems to be that `resolveGitRepo()` is calling `execGit()` without passing the cwd parameter. Without this parameter, `execGit()` is forced to fall back to `process.cwd()`, which in my case is NOT a proper git …

Add missing cwd option when calling execGit function

---

bin/lint-staged.js
lib/index.js
lib/loadConfig.js

This PR fixes the `--debug` option. Not sure when it broke, but this makes it work again:

fix: using `--debug` option enables debug mode

---

lib/makeCmdTasks.js
lib/resolveTaskFn.js
lib/runAll.js
test/makeCmdTasks.spec.js
test/resolveTaskFn.spec.js

I noticed that the `execa` task spawning linters wasn't getting passed the `cwd` option, this might explain difficulties with ESLint picking up configuration, for example. Previously tasks were always run in the `process.cwd()`, but it might be explicitly something else.

fix: always run non-git tasks in the current working directory

---

jest.config.js
lib/loadConfig.js
lib/resolveConfig.js
test/index.spec.js
test/index2.spec.js
test/integration.test.js
test/loadConfig.spec.js

ES modules do not have require() available, we must construct it first.
This fixes the CLI when passing `--config my-config-package`, broken in v12.0.0.
The tests didn't catch this because Jest still doesn't support mocking ESM, and there's really no way to write a test for this right now. I verified it locally like this:
```js
// broken.mjs
console.log(require.resolve('react'))
```
```sh
$ node -v
v14.18.1
$ node ./broken.mjs
file:///path/to/broken.mjs:1
console.log(require.resolve('react'))
^
ReferenceError: require is not defined in ES module scope, you can use import instead
at file:///Users/daniel/code/front-end-shared-config/resolve-config.mjs:1:13
at ModuleJob.run (internal/modules/esm/module_job.js:183:25)
at async Loader.import (internal/modules/esm/loader.js:178:24)
at async …
```

fix: Resolve config modules with ESM createRequire()

---

lib/getConfigGroups.js
test/getConfigGroups.spec.js

Previously lint-staged would throw if any staged file was missing a config,
but it should be enough that at least one file has a matching config.
Fixes https://github.com/okonet/lint-staged/issues/1087

fix: only throw if no configurations were found

---

lib/getConfigGroups.js
lib/runAll.js
test/getConfigGroups.spec.js
test/integration.test.js

This PR makes lint-staged always search for a configuration file from the `cwd`, even if no staged files are inside this. This fixes https://github.com/okonet/lint-staged/issues/1092.

fix: always search config from `cwd` first

---

README.md
bin/lint-staged.js
lib/index.js
lib/runAll.js
lib/validateOptions.js
test/validateOptions.spec.js

This PR exposes the `--cwd` option, previously only available in the Node.js API. It also adds a debug log output for the current value, and whether it was explicit or not.

feat: add `--cwd` option for overriding task directory

---

lib/resolveGitRepo.js

We're using [git-repo](https://gerrit.googlesource.com/git-repo/) and it creates .git directories as symlinks.
Current .git path resolution doesn't recognize it and throws an error.

fix: handles symlink .git paths

---

lib/runAll.js
test/integration.test.js
test/runAll.spec.js

This PR makes tasks run in the directory of the config file, when there are multiple configuration files.
In the case of only a single configuration file, tasks will still run in the current working directory, so this shouldn't really be a breaking change.
I also added some debug logging to `getConfigGroups`.
What do you think, @okonet?

fix: use config directory as cwd, when multiple configs present

---

lib/getConfigGroups.js
lib/getStagedFiles.js
lib/loadConfig.js
lib/parseGitZOutput.js
lib/runAll.js
lib/searchConfigs.js
test/getConfigGroups.spec.js
test/parseGitZOutput.spec.js
test/runAll.spec.js

This PR searches for all configurations inside the git repo, instead of only those matching the staged files. It's currently only used for the `hasMultipleConfigs` check, but in the future it will also be used to fix "parent directory" globs, which are currently not working.
Without this fix, `hasMultipleConfigs` would be `false` if you only staged files matching a single config, and thus the CWD would be wrong.

fix: search all configs regardless of staged files

---

test/integration.test.js
test/utils/crossPlatform.js

Apparently, `touch` is one of the numerous tools that GitHub installs in its actions image. But it is generally not available on Windows systems.
Plus, there was a missing await in a write file function that caused issues at least on my desktop Windows 11.

chore: don't use `touch` on windows

---

lib/resolveTaskFn.js
package-lock.json
package.json
test/__mocks__/execa.js
test/__mocks__/pidtree.js
test/resolveTaskFn.spec.js
test/resolveTaskFn.unmocked.spec.js
test/runAll.spec.js
test/utils/createExecaReturnValue.js

This kills already running tasks as soon as an error is emitted by another task. Making it possible to interrupt concurrently running tasks on first failure.
Aside from the included unmocked test, you can also try it out by staging a linting error and changing the lint-staged configuration in this repo to `.lintstagedrc.mjs` with the following content:
```
export default {
"*.js": "eslint",
"*.{js,ts}": () => "npm run test",
}
```
... and running:
`node ./bin/lint-staged.js`
I have changed the precedence of the tags, since I think it would be confusing to users to see the signals when we consciously kill tasks. (With the previous order, they would have seen `SIGTERM`. This way, it is `KILLED`.)
There are two minor caveats:
- It doesn't work with `shell: true`.
- For this to work with npm …

fix: kill other running tasks on failure

---

lib/getRenderer.js
lib/runAll.js
test/getRenderer.spec.js
test/index2.spec.js

I was kind of on the fence for whether forcing animation/update should be determined by `FORCE_COLOR` or a new command line flag or environment variable.
I went with `FORCE_COLOR` because I think 99.9% of the time if you want to force colors, then you also want animation/update. If you're forcing colors, then you're using a modern terminal, which should support animation/update. Let me know if that makes sense to you or if you think differently!
Lastly, while I was making changes here I also noticed that the fallback renderer can be non-silent even when the main renderer is silent. So if you passed the quiet option and the fallback renderer was chosen, then it wouldn't be quiet. I've fixed that as well.
Closes #693

Force update rendering for forced colors and ensure quiet rendering when requested

---

lib/resolveTaskFn.js

The recently merged #1117 (and the 12.3.6 release itself) introduced a quite dangerous defect in the clean-up logic for failed multi-process linter runs.
I've made an attempt to fix those, but unfortunately I'm not sure I can quickly come up with a suitable test coverage for the fixes provided.
Reason being is that I'm not sure how to incorporate such low-level checks into integration-like output matchers I saw in the existing suites.
Maybe you do not even cover such stuff typically? 
The first quite simple issue is just missed code bug. We have 
```js
ids.forEach(process.kill)
```
which actually runs as 
```js
ids.forEach((id, index) => process.kill(id, index))
```
Maybe it was doing fine during testing, but in my environment on Windows machine it caused the whole thing to halt with …

fix: avoid overkilling execa and child processes asynchronously on error

---

.github/workflows/main.yml
lib/searchConfigs.js
test/integration.test.js
test/searchConfigs.spec.js

Fixes https://github.com/okonet/lint-staged/issues/1141
The main change was:
```diff
--- configs[filepath] = validateConfig(config, filepath, logger)
+++ configs[configPath] = validateConfig(config, filepath, logger)
```
where `configPath` is the discovered possible file, and `filepath` is returned by `lilconfig` after loading it. In the case of symlinks, the latter points to the real file so it shouldn't be used to resolve staged files (Might be outside the entire git repo, for example.

fix: correctly handle symlinked config files

---

bin/lint-staged.js

1. Fixed default value of `maxArgLength` from `null` to `undefined`, so that `getMaxArgLength` could be called to receive default value inside `lintStaged`
2. Added default default value to `--max-arg-length` cli option, so it always would be a number (now it can be boolean)

fix: correctly handle --max-arg-length cli option

---

README.md

I found a comma missing in the README code.

docs: fix the missing comma in the README.md code

---

.github/workflows/main.yml
README.md
bin/lint-staged.js
lib/chunkFiles.js
lib/dynamicImport.js
lib/execGit.js
lib/file.js
lib/generateTasks.js
lib/getStagedFiles.js
lib/gitWorkflow.js
lib/groupFilesByConfig.js
lib/index.js
lib/printTaskOutput.js
lib/resolveConfig.js
lib/resolveGitRepo.js
lib/resolveTaskFn.js
lib/runAll.js
lib/searchConfigs.js
lib/validateOptions.js
package-lock.json
package.json
test/__mocks__/execa.js
test/execGit.spec.js
test/loadConfig.spec.js
test/makeCmdTasks.spec.js
test/resolveTaskFn.spec.js
test/runAll.spec.js

This PR:
- creates a breaking change to remove support for Node.js 12 since it's now EOL
- adds some fancy new stuff: `node:` protocol imports and `?.` optional chaining
- finally updates `execa@6`, and also `yaml@2`
- removes the `supports-color` dependency since `colorette` already exports a similar flag
I'm keeping it as a draft because it's rebased to https://github.com/okonet/lint-staged/pull/1159, but what do you think @okonet ?

Remove Node.js 12 support

---

lib/gitWorkflow.js
test/unit/getBackupStash.spec.js

This simple patch fixes https://github.com/okonet/lint-staged/issues/1121 by detecting MSYS2 shell via env variables set by MSYS2 (https://github.com/msys2/MSYS2-packages/blob/master/filesystem/msys2_shell.cmd) and adds escaped braces if MSYS2 is found.

fix: correctly handle git stash when using MSYS2

---

package.json

Expose cli entrance will be convenient for developers who want to integrate `lint-stage` cli.

feat: expose cli entrance

---

README.md

Hello!
Thanks for all your work on this project - it's awesome! This PR updates a link to my blog in the README - I replatformed from Blogger to Docusaurus and my URLs changed. I've got redirects in place, so the link still works, but it's always better to have the direct link I think!
- [Prettier your CSharp with `dotnet-format` and `lint-staged`](https://blog.johnnyreilly.com/2020/12/22/prettier-your-csharp-with-dotnet-format-and-lint-staged)

fix: update link to blog post

---

README.md

Hello!
Thanks for your amazing work!  My blog has moved from blog.johnnyreilly.com to johnnyreilly.com; this PR updates the link to reflect that. (There's a 301 in place but it's good to cover all bases)
https://github.com/johnnyreilly/blog.johnnyreilly.com/pull/393

docs: blog.johnnyreilly.com -> johnnyreilly.com

---

README.md

Fixes a couple broken links in the readme.

docs: Fix broken links in readme

---

lib/index.js

fix: fix stash still true when diff is not undefined

fix: fix stash still true when diff is not undefined

---

lib/gitWorkflow.js
test/unit/getBackupStash.spec.js

Following the discussion in #1267 I'm making this PR here to make the suggested change. Please see the issue for more details.
This also means we can remove the MSYS workaround, and the corresponding test.

Use index-based stash references

---

.github/workflows/main.yml

This PR bumps a minor version, making it possible to publish a new npm version under the `latest` tag. From this PR `semantic-release` inadvertently released patch versions to `next` without adding the `-next` postfix.
It also disables `semantic-release` from running for the `next` branch, until the issue is solved.

Minor Version Bump

---

lib/loadConfig.js
test/unit/loadConfig.spec.js

This PR hides the JSON parser error when trying to load _lint-staged_ config from an invalid package.json file:
```
% node bin/lint-staged.js
SyntaxError: Unexpected end of JSON input
at JSON.parse (<anonymous>)
at jsonParse (file:///Users/iiro/git/lint-staged/lib/loadConfig.js:30:43)
at Object.load (/Users/iiro/git/lint-staged/node_modules/lilconfig/dist/index.js:148:35)
at async loadConfig (file:///Users/iiro/git/lint-staged/lib/loadConfig.js:65:20)
at async Promise.all (index 1)
at async searchConfigs (file:///Users/iiro/git/lint-staged/lib/searchConfigs.js:84:3)
at async runAll (file:///Users/iiro/git/lint-staged/lib/runAll.js:129:24)
at async lintStaged (file:///Users/iiro/git/lint-staged/lib/index.js:108:17)
✔ Preparing lint-staged...
✔ Running tasks for staged files...
✔ Applying …
```

fix: ignore "package.json" as config file when it's invalid JSON

---

bin/lint-staged.js
lib/messages.js
lib/readStdin.js
package-lock.json
package.json
test/e2e/__utils__/getLintStagedExecutor.js
test/e2e/stdin-config.test.js
test/unit/readStdin.spec.js

Fixes https://github.com/okonet/lint-staged/issues/1316, which was broken when switching to async `node:fs/promises`. This feature didn't have any tests, and I was lazy it seems...

fix: correctly read config from stdin

---

.changeset/dull-moons-double.md
.github/workflows/push.yml
package-lock.json
package.json

**Require at least Node.js 18.12.0**
This release drops support for Node.js 16, which is EOL after 2023-09-11.
Please upgrade your Node.js to the latest version.
Additionally, all dependencies have been updated to their latest versions.

feat: require at least Node.js 18.12.0

---

.changeset/sixty-stingrays-glow.md
lib/makeCmdTasks.js
test/unit/makeCmdTasks.spec.js

This prevents the task command to change the files array by inadvertence. It happened to me and I took a long moment to diagnose the issue.
```
Task in generateTasks
{
pattern: 'apps/dummy/dummy/**/*.js',
commands: [Function: apps/dummy/dummy/**/*.js],
fileList: [
'/Users/lounesksouri/dummy/apps/dummy/dummy/src/config.js'
]
}
Task in runAll after makeCmdTasks
{
pattern: 'apps/dummy/dummy/**/*.js',
commands: [Function: apps/dummy/dummy/**/*.js],
fileList: []
}
```

fix: run task command on files deep copy

---

.changeset/early-zoos-buy.md
README.md
lib/loadConfig.js
test/unit/__mocks__/package.yml
test/unit/loadConfig.spec.js

Add support for `package.y`[`a`]`ml`

---

.changeset/empty-gifts-leave.md
README.md
bin/lint-staged.js
lib/index.js
lib/messages.js
lib/runAll.js
lib/state.js
test/integration/__fixtures__/files.js
test/integration/no-hide-partially-staged.test.js
test/integration/no-stash.test.js

Local copy of https://github.com/lint-staged/lint-staged/pull/1294

feat: `--no-stash` flag implies `--no-hide-partially-staged`

---

.changeset/dirty-eagles-decide.md
.github/workflows/install.yml
.github/workflows/push.yml
lib/execGit.js
lib/resolveTaskFn.js
test/unit/execGit.spec.js
test/unit/makeCmdTasks.spec.js
test/unit/resolveTaskFn.spec.js
test/unit/resolveTaskFn.unmocked.spec.js

This should fix https://github.com/lint-staged/lint-staged/issues/1293 and https://github.com/lint-staged/lint-staged/issues/1019

fix: ignore stdin of spawned commands

---

.changeset/lovely-balloons-doubt.md
.changeset/tender-frogs-do.md
package-lock.json
package.json

This PR updates `micromatch` to  version 4.0.7 and adjusts all direct dependency version ranges to allow "_approximately equivalent versions_" by using the `~` character; this means a more recent patch version is allowed.

Dependency version ranges

---

.changeset/smart-pets-melt.md
lib/loadConfig.js
lib/messages.js
lib/validateConfig.js
test/unit/__snapshots__/validateConfig.spec.js.snap
test/unit/loadConfig.spec.js

Fixes https://github.com/lint-staged/lint-staged/issues/1421 by adding more generic error logging when `validateConfig` function throws for unknown reasons.

fix: improve error logging when failing to parse config file

---

.changeset/stale-ants-hope.md
lib/resolveGitRepo.js
test/unit/resolveGitRepo.spec.js

Use native "git rev-parse" commands to determine git repo root directory and the .git config directory, instead of using custom logic. This hopefully makes path resolution more robust on non-POSIX systems.

fix: use native git command to get top-level directory for repo

---

.changeset/itchy-shrimps-shake.md
lib/resolveGitRepo.js

Fixes https://github.com/lint-staged/lint-staged/issues/1437

fix: drop option to support earlier Git versions

---

.husky/commit-msg
.husky/pre-commit
.husky/pre-push
README.md

In latest release of Husky ([v9.1.2](https://github.com/typicode/husky/releases/tag/v9.1.2)) it is stated:
> Show a message instead of automatically removing deprecated code.
>
> This only concerns projects that still have the following code in their hooks:
> ```diff
> - #!/usr/bin/env sh # <- This is deprecated, remove it
> - . "$(dirname -- "$0")/_/husky.sh"  # <- This is deprecated, remove it
> 
> # Rest of your hook code
So I both updated README and Husky hooks, tested them by this procedure:
1. Installed NPM packages;
2. Initialized Husky by `husky` command;
3. Tried to push empty commit with name `test: testing Husky hooks after update`
Git accepted commit, so I think it's a good sign, in my commits I provided source and link to the Husky's release patchnote to avoid confusion in …
```

Update and edit Husky to v9.1.2 according to latest patchnotes

---

.changeset/dull-pants-remain.md
lib/runAll.js

Node.js has a default max listener limit of 10 and emits a warning when going over:
```
(node:3528) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 lint-staged:taskError listeners added to [EventEmitter]. MaxListeners is 10. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
```

fix: set max event listeners to the number of tasks

---

.changeset/chilled-rules-drive.md
lib/resolveTaskFn.js
test/unit/resolveTaskFn.spec.js

Execution of eslint using lint-staged fails when file path contains whitespaces and some workaround similar to those described in #773 is needed.
Example: For the file `/path/to/file with spaces.js`, it fails with:
```
No files matching the pattern "/path/to/file" were found.
Please check for typing mistakes in the pattern.
```
ESlint debug print contains message like this:
```
2024-12-10T06:37:22.698Z eslint:cli CLI args: [ '--config', 'eslint.config.js', '--debug', '--fix', '/path/to/file', 'with', 'spaces.js' ]
```
However, the `execa` library supports a simple space [backlash escaping](https://github.com/sindresorhus/execa/blob/f4b8b3ab601c94d1503f1010822952758dcc6350/lib/command.js#L32-L37) which can be leveraged here.

fix: running eslint on filenames containing spaces

---

.changeset/polite-plums-fly.md
.changeset/smart-adults-approve.md
.changeset/soft-ties-poke.md
README.md
bin/lint-staged.js
lib/gitWorkflow.js
lib/index.js
lib/messages.js
lib/runAll.js
lib/state.js
test/integration/git-lock-file.test.js
test/unit/getBackupStash.spec.js
test/unit/index3.spec.js

This PR adds some more help messages about the `git stash` backup _lint-staged_ creates by default:
1. always visible at the end of `lint-staged --help` output
2. previously the message was only visible when "git errors" occurred, now it's also visible whenever the task to cleanup the backup is skipped (so that the stash is left behind)
3. Finally, the first task title `Preparing lint-staged...` will be changed to `Backing up original state..` and `Backed up original state in git stash` (unless disabled with `--no-stash`)

Add more help messages about "git stash"

---

.changeset/lucky-rules-teach.md
lib/state.js
test/integration/allow-empty.test.js

See the changeset for description: [.changeset/lucky-rules-teach.md](https://github.com/lint-staged/lint-staged/blob/4c4b9f588ef52de498855e3c6095479d5998d4fc/.changeset/lucky-rules-teach.md)

feat: do not reset to original state when preventing empty commit

---

.changeset/dry-words-talk.md
.github/workflows/pull-requests.yml
lib/getDiffCommand.js
lib/getStagedFiles.js
lib/gitWorkflow.js
test/unit/getDiffCommand.spec.js
test/unit/getStagedFiles.spec.js

The previous command
```
git submodule foreach echo $displaypath
```
breaks when encountering uninitialized submodules, causing _lint-staged_ to crash with "_Failed to get staged files!_".
This PR improves the logic by using the `--raw` flag with `git diff` to get access to the object modes of the staged files, where mode `160000` is for the submodule directory.

fix: handle uninitialized submodules when listing staged files

---

.changeset/rare-fishes-call.md
README.md
lib/resolveTaskFn.js
package-lock.json
package.json
test/unit/__utils__/mockExecaReturnValue.js
test/unit/resolveTaskFn.spec.js

This PR updates to the latest `execa` version 9, and bumps minimum required Node.js version from 18.12.0 to 18.19.0.
~~I wouldn't consider this a breaking change because 18 LTS is still receiving updates and the current version is at 18.20.2.~~
EDIT: Let's make this a breaking change; I'll also remove the deprecated "_advanced config_" validation code.

Update Execa v9

---

.changeset/neat-parrots-watch.md
MIGRATION.md
README.md
bin/lint-staged.js
lib/index.d.ts
lib/index.js
lib/makeCmdTasks.js
lib/resolveTaskFn.js
lib/runAll.js
lib/validateOptions.js
package.json
test/integration/__utils__/isWindows.js
test/integration/git-lock-file.test.js
test/integration/multiple-config-files.test.js
test/integration/parent-globs.test.js
test/unit/makeCmdTasks.spec.js
test/unit/resolveTaskFn.spec.js
test/unit/resolveTaskFn.unmocked.spec.js
test/unit/validateOptions.spec.js

Parsing shell commands is unsafe, and I don't think _lint-staged_ needs to directly support it. Users can create a wrapper shell script instead (or even a JS script), since _lint-staged_ passed the matched staged files as arguments anyway:
```shell
#!/bin/bash
echo "Staged files: $@"
```

feat: remove `--shell` flag support

---

.changeset/happy-cougars-wish.md
lib/getStagedFiles.js
test/unit/getStagedFiles.spec.js

After upgrading `lint-staged` to `v15.5.1`, it keeps throwing `Failed to get staged files!` for me. Did some debugging and realised that it does not support filenames with colon any more. 
Potentially fixing #1543.

fix: handle colon characters in staged filenames

---

.changeset/yummy-poems-agree.md
lib/getStagedFiles.js
test/integration/symlinked-staged-files.test.js

Symlinks themselves aren't really relevant "staged files", because the actual file contents are elsewhere. Previously linters probably either resolved to the absolute path themselves, or errored out.
Now that we use the Git Diff raw output since https://github.com/lint-staged/lint-staged/pull/1533, we can filter them out.

feat: leave out symlinks from list of staged files

---

.changeset/real-clowns-smile.md
lib/chunkFiles.js

Replaced string concatenation approach with direct length calculation to reduce memory usage. The current implementation creates an intermediate array of file paths and then joins them into a single large string to calculate the total length. The new approach uses reduce() to calculate the total length in a single pass, eliminating unnecessary allocations.

fix: optimize file list length calculation

---

lib/searchConfigs.js

Replace two separate `git ls-files` executions with one combined call using `--cached` and `--others` flags. This reduces process creation overhead, especially on Windows where CreateProcess is expensive.

perf: combine `git ls-files` calls into single process

---

.changeset/upset-beans-mate.md
package.json

fix: add root-level "types" field to package.json

---

.changeset/fifty-tires-itch.md
README.md
bin/lint-staged.js
lib/gitWorkflow.js
lib/index.d.ts
lib/index.js
lib/messages.js
lib/runAll.js
lib/state.js
lib/symbols.js
test/integration/exit-code.test.js

In line with `git diff --exit-code`, make _lint-staged_ exit with code 1 (and prevent commit) when tasks modify any files. This is achieved by calculating SHA-256 hash of `git diff --patch --unified=0` before and after running tasks, before running `git add` on them.
The result is _lint-staged_ will fail the commit if tasks change any files. When combined with `--no-revert`, it forces the developer to manually add changes and try to commit again. Fixes https://github.com/lint-staged/lint-staged/issues/977 and https://github.com/lint-staged/lint-staged/issues/1599

feat: add --exit-code flag

---

.changeset/healthy-oranges-walk.md
README.md
bin/lint-staged.js
lib/index.d.ts
lib/index.js
lib/runAll.js
test/integration/continue-on-error.test.js
test/unit/runAll.spec.js

Adds a new CLI option `--continue-on-error` that
allows lint-staged to continue running all
configured tasks even if one fails, enabling users to see all linting errors at once instead of
stopping at the first failure.
- Add --continue-on-error CLI flag with Commander.js
- Update runAll.js to use exitOnError: !continueOnError in Listr2 configs
- Maintain backward compatibility (default behavior unchanged)
- Add comprehensive unit and integration tests with proper error simulation
- Update JSDoc parameter documentation
Addresses: https://github.com/lint-staged/lint-staged/issues/1590

feat: add --continue-on-error flag

---

.changeset/evil-hats-doubt.md
lib/runAll.js

Run `getStagedFiles()` and `searchConfigs()` concurrently. This should eliminate potential sequential I/O

perf: parallelize staged files retrieval and config search

---

.changeset/dependabot-2838997856.md
.changeset/smart-mugs-tap.md
README.md
bin/lint-staged.js
lib/chunkFiles.js
lib/debug.js
lib/execGit.js
lib/file.js
lib/generateTasks.js
lib/getFunctionTask.js
lib/getSpawnedTask.js
lib/getSpawnedTasks.js
lib/gitWorkflow.js
lib/groupFilesByConfig.js
lib/index.js
lib/loadConfig.js
lib/resolveGitRepo.js
lib/runAll.js
lib/searchConfigs.js
lib/validateConfig.js
lib/validateOptions.js
package-lock.json
package.json
test/unit/debug.spec.js
test/unit/index.spec.js

Remove [debug](https://github.com/debug-js/debug) as a dependency due to recent malware issue; read more at https://github.com/debug-js/debug/issues/1005.

feat: remove `debug` as a dependency
